url: http://blog.lacti.me
username: lacti
repo: https://github.com/lacti/lacti.github.io
branch: source
relative_source: .
destination: ../site-deploy/

permalink: pretty
highlighter: pygments
markdown: redcarpet
redcarpet:
  extensions:
    - no_intra_emphasis
    - fenced_code_blocks
    - autolink
    - strikethrough
    - superscript
    - tables

exclude:
  - Rakefile.rb
  - CNAME
  - README.md
  - Gemfile
  - .travis.yml
  - vendor